---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      application: tcp-echo
  template:
    metadata:
      labels:
        application: tcp-echo
    spec:
      containers:
      - name: echo
        image: quay.io/skupper/tcp-echo
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
  - port: 9999
    targetPort: 9090
  selector:
    application: tcp-echo
---
